# Generated by Django 5.1.7 on 2025-04-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='collection',
        ),
    ]
