# Generated by Django 5.1.7 on 2025-04-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_book_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giaotrinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('uri', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_images/')),
            ],
        ),
    ]
