# Generated by Django 5.1.7 on 2026-04-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_book_available_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
