# Generated by Django 5.1.7 on 2026-06-13 06:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_book_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhistory',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('cong_nghe', 'Công nghệ - CNTT'), ('van_hoc', 'Văn học'), ('kinh_te', 'Kinh tế'), ('ngoai_ngu', 'Ngoại ngữ'), ('khoa_hoc', 'Khoa học tự nhiên'), ('xa_hoi', 'Khoa học xã hội'), ('giao_duc', 'Giáo dục - Tâm lý'), ('ky_thuat', 'Kỹ thuật - Công nghệ'), ('khac', 'Khác')], default='khac', max_length=50, verbose_name='Thể loại'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Số sao')),
                ('comment', models.TextField(blank=True, verbose_name='Nhận xét')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.book', verbose_name='Sách')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
