# Generated by Django 5.1.7 on 2026-06-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_userhistory_options_book_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
