# Generated by Django 5.1.7 on 2026-06-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_borrowrecord_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Giaotrinh',
        ),
    ]
