# Generated by Django 5.1.7 on 2026-06-25 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delete_giaotrinh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
    ]
